site_name: "Blog"
site_author: "Marvin-NM"
copyright: " 2025 MarvinNNM - Tous droits r√©server"
theme:
  name: material
  feature:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.action.edit
    - content.code.copy
  palette:
    scheme: slate
    priamry: deep purple

plugins:
  - search
  - tags
  - blog
  - social
    
nav:
  - Home: index.md
